version: '3.9'

networks:
  network:

services:

  backend:
    container_name: backend
    build:
      context: ./back
    image: img_backend
    volumes:
      - ./back/src:/app/src
    ports:
      - 5001:5000
    networks:
      - network
    restart: unless-stopped

  front:
    container_name: frontend
    build:
      context: ./front
    image: img_frontend
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
    ports:
      - 3000:3000
    networks:
      - network
    restart: unless-stopped