version: '3.9'

services:

  backend:
    container_name: backend
    build:
      context: ./back
    image: img_backend
    volumes:
      - ./back:/app
    ports:
      - 5001:5000
    env_file:
      - ./dockerEnv/backend.env
    restart: unless-stopped

  front:
    container_name: frontend
    build:
      context: ./front
    image: img_frontend
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
    ports:
      - 3000:3000
    env_file:
      - ./dockerEnv/frontend.env
    restart: unless-stopped

  db-server:
    container_name: db-server
    image: postgres
    ports:
    - 5432:5432
    env_file:
      - ./dockerEnv/db-server.env
    volumes:
      - ./db-data/:/var/lib/postgresql/data
      # - /Users/$USER/db-data/:/var/lib/postgresql/data
    restart: unless-stopped

  db-client:
    container_name: db-client
    image: img_db-client
    build:
      context: ./db-client
    ports:
      - 5050:80
    env_file:
      - ./dockerEnv/db-client.env
    restart: unless-stopped